### ISSUE TITLE
请问能否将最新的代码传上来呢，我自己运行的话会遇到下方的错误，并且还是解决不了，问题和主子线程相关，目前不知道怎么解决~

### ISSUE THREAD

**Issue by yoyo115956** [fate-ubw/MarginExpand#1]
照着github的代码运行，发现会不断地有下方的错误，并且pdf打开什么也不会显示，如下图所示。感觉和主子线程相关，目前不知道怎么解决想和您交流一下，如果您方便把最新的代码上传上来就太感谢了！
QObject::setParent: Cannot set parent, new parent is in a different thread
same
same
same
same
QObject::setParent: Cannot set parent, new parent is in a different thread
same
same
same
![image](https://github.com/fate-ubw/MarginExpand/assets/56446859/276d30a0-2ba4-401a-8528-59c0e7ed45a2)

**Comment by yoyo115956** [comment]
主要是希望能够实现一下在pdf下方增加边距的功能，看到您还未实现想尝试看看。然而这里就卡住了，也研究了一天了还是不太清楚怎么处理，麻烦您帮忙解答哇！

**Comment by fate-ubw** [comment]
看到您的issue非常的开心，没有想到随手做的小玩意真的会有人使用，代码是初学python的时候编写的，实在说不上规范。关于下方也想增加边距其实实现起来应该没有那么困难。
推测原因：
1-我推测这个bug是qt环境没有安装正确，我实在python环境中安装了pyqt，并且将全部相关的包打包在了软件中，可以直接调用，怀疑是和你电脑的qt环境冲突了，可以卸载qt 尝试一下。
2-我看到pdf后面还有dot符号，试试其他未经过编辑的pdf文件
3-使用我新编写的2.0版本的marginExpand，我近期努力将2.0版本上传好，但是这一个版本依旧没有更新下方增加边距的功能，仅仅是优化了文件查找功能

**Comment by fate-ubw** [comment]
今天突然想起来，你可以尝试让chatgpt帮助你实现这个功能，将全部的代码丢上去，然后让gpt帮助你生成代码
