### ISSUE TITLE
来感谢的🙏

### ISSUE THREAD

**Issue by wisRen** [fate-ubw/MarginExpand#2]
1. 非常好的工具🎉
2. 检索了一下，应该是目前可以PDF扩展“白边”的最好工具
3. 期待后续可以实现，左边或上下边可以扩展“白边”，及比如：自由定义白边宽度。

**Comment by fate-ubw** [comment]
哇没想到真的有人会用MarginExpand ！！！！ 当初只是为了解决自己需求开发的一个小工具，考虑到大部分的用户是学生为主，并且目的是记录笔记，所以为了简单操作就设定了 4 种页面宽度，从上手难度上讲预设要比自由定义少 2,3 个点击动作，所以就没有开发自由定义的功能。现在工程能力比以往好了很多，我找空可以重新开发一遍这个小工具，非常感谢支持

**Comment by fate-ubw** [comment]
> 1. 非常好的工具🎉
> 2. 检索了一下，应该是目前可以PDF扩展“白边”的最好工具
> 3. 期待后续可以实现，左边或上下边可以扩展“白边”，及比如：自由定义白边宽度。


哇没想到真的有人会用MarginExpand ！！！！ 当初只是为了解决自己需求开发的一个小工具，考虑到大部分的用户是学生为主，并且目的是记录笔记，所以为了简单操作就设定了 4 种页面宽度，从上手难度上讲预设要比自由定义少 2,3 个点击动作，所以就没有开发自由定义的功能。现在工程能力比以往好了很多，我找空可以重新开发一遍这个小工具，非常感谢支持
